-- 신규 설치용. 기존 scheduler.interviews에는 admin-auth-migration.sql을 실행하세요.
create schema if not exists scheduler;

create table if not exists scheduler.interviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  email text check (char_length(email) <= 254 and email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  phone text not null check (char_length(phone) between 8 and 20 and phone ~ '^[0-9+() -]+$'),
  interview_date date not null,
  interview_time text not null check (interview_time ~ '^([01][0-9]|2[0-3]):(00|30)$'),
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index if not exists interviews_confirmed_slot_key
  on scheduler.interviews (interview_date, interview_time) where status = 'confirmed';

-- 이어서 admin-auth-migration.sql을 실행하세요.
